@startsalt
skinparam dpi 300
{{+
    {{ Регистрационные данные }}
    {{ }}
    {{ "Логин              " }}
    {{ "E-mail             " }}
    {{ "Имя для обращения  " }}
    {{ }}
    [ ОК ]
}}
@endsalt
